// Internal durable workflow payload messages shared by workflow families.

// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.js"
// @generated from file onequery/workflow/v1/common.proto (package onequery.workflow.v1, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file onequery/workflow/v1/common.proto.
 */
export const file_onequery_workflow_v1_common: GenFile /*@__PURE__*/ = fileDesc(
  "CiFvbmVxdWVyeS93b3JrZmxvdy92MS9jb21tb24ucHJvdG8SFG9uZXF1ZXJ5LndvcmtmbG93LnYxKsQBChhXb3JrZmxvd0RhdGFTb3VyY2VTdGF0dXMSKwonV09SS0ZMT1dfREFUQV9TT1VSQ0VfU1RBVFVTX1VOU1BFQ0lGSUVEEAASJgoiV09SS0ZMT1dfREFUQV9TT1VSQ0VfU1RBVFVTX0FDVElWRRABEiUKIVdPUktGTE9XX0RBVEFfU09VUkNFX1NUQVRVU19FUlJPUhACEiwKKFdPUktGTE9XX0RBVEFfU09VUkNFX1NUQVRVU19ESVNDT05ORUNURUQQA2IIZWRpdGlvbnNw6Ac"
);

/**
 * @generated from enum onequery.workflow.v1.WorkflowDataSourceStatus
 */
export enum WorkflowDataSourceStatus {
  /**
   * @generated from enum value: WORKFLOW_DATA_SOURCE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: WORKFLOW_DATA_SOURCE_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: WORKFLOW_DATA_SOURCE_STATUS_ERROR = 2;
   */
  ERROR = 2,

  /**
   * @generated from enum value: WORKFLOW_DATA_SOURCE_STATUS_DISCONNECTED = 3;
   */
  DISCONNECTED = 3,
}

/**
 * Describes the enum onequery.workflow.v1.WorkflowDataSourceStatus.
 */
export const WorkflowDataSourceStatusSchema: GenEnum<WorkflowDataSourceStatus> /*@__PURE__*/ =
  enumDesc(file_onequery_workflow_v1_common, 0);
