import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { WORKSPACE_DEV_SECRETS_FILENAME } from "@onequery/config/workspace-dev";
import { describe, expect, it } from "vitest";

import { loadWorkspaceDev } from "./workspace-dev";
import { ensureWorkspaceDevSecretsFileSync } from "./workspace-dev-init";

function createTempRootDir(): string {
  return mkdtempSync(join(tmpdir(), "onequery-workspace-dev-init-"));
}

function normalizeWorkspaceDevSecretsFile(contents: string): string {
  return contents
    .replace(/secret = "[^"]+"/, 'secret = "<generated-auth-secret>"')
    .replace(
      /master_encryption_key = "[^"]+"/,
      'master_encryption_key = "<generated-master-encryption-key>"'
    )
    .replace(
      /enrollment_token = "[^"]+"/,
      'enrollment_token = "<generated-enrollment-token>"'
    );
}

describe("ensureWorkspaceDevSecretsFileSync", () => {
  it("creates repo-local workspace-dev secrets when missing", () => {
    const rootDir = createTempRootDir();

    try {
      const result = ensureWorkspaceDevSecretsFileSync({
        rootDir,
      });

      const contents = readFileSync(result.path, "utf8");
      expect({
        contents: normalizeWorkspaceDevSecretsFile(contents),
        result: {
          ...result,
          path: result.path.replace(rootDir, "<rootDir>"),
        },
      }).toEqual({
        contents: [
          "# Generated by OneQuery local bootstrap.",
          "# This file is local-only and intentionally gitignored.",
          "",
          "[auth]",
          'secret = "<generated-auth-secret>"',
          "",
          "[crypto]",
          'master_encryption_key = "<generated-master-encryption-key>"',
          "",
          "[connectors]",
          'enrollment_token = "<generated-enrollment-token>"',
          "",
        ].join("\n"),
        result: {
          created: true,
          path: "<rootDir>/.onequery/dev/secrets.toml",
        },
      });

      const resolved = loadWorkspaceDev({
        rootDir,
      });
      expect(resolved.auth.secret).toEqual(expect.any(String));
      expect(resolved.connectors.enrollmentToken).toEqual(expect.any(String));
      expect(resolved.crypto.masterEncryptionKey).toEqual(expect.any(String));
    } finally {
      rmSync(rootDir, { force: true, recursive: true });
    }
  });

  it("keeps an existing secrets file unchanged", () => {
    const rootDir = createTempRootDir();
    const secretsPath = join(
      rootDir,
      ".onequery",
      "dev",
      WORKSPACE_DEV_SECRETS_FILENAME
    );
    const existingContents = [
      "[auth]",
      'secret = "existing-auth-secret"',
      "",
      "[crypto]",
      'master_encryption_key = "ZXhpc3RpbmctbWFzdGVyLWtleQ=="',
      "",
      "[connectors]",
      'enrollment_token = "existing-enrollment-token"',
      "",
    ].join("\n");

    try {
      ensureWorkspaceDevSecretsFileSync({
        rootDir,
      });
      writeFileSync(secretsPath, existingContents, "utf8");

      expect(
        ensureWorkspaceDevSecretsFileSync({
          rootDir,
        })
      ).toEqual({
        created: false,
        path: secretsPath,
      });
      expect(readFileSync(secretsPath, "utf8")).toBe(existingContents);
    } finally {
      rmSync(rootDir, { force: true, recursive: true });
    }
  });
});
