[tools]
"aqua:bufbuild/buf" = "1.67.0"
"aqua:casey/just" = "1.48.1"
"aqua:orhun/git-cliff" = "2.12.0"
"aqua:rhysd/actionlint" = "1.7.11"
"aqua:mitsuhiko/insta" = "1.47.1"
"cargo:cargo-expand" = "1.0.121"
"cargo:cargo-nextest" = "0.9.132"
"npm:@antfu/ni" = "30.0.0"
"npm:agent-browser" = "0.25.5"
"npm:@hono/cli" = "0.1.10"

[settings]
npm.bun = true
# tools can read the versions files used by other version managers
idiomatic_version_file_enable_tools = ["bun", "node", "rust"]

[env]
_.path = "./"
