// Private Connect service for self-host runtime lifecycle control.

// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.js"
// @generated from file onequery/runtime/v1/control.proto (package onequery.runtime.v1, edition 2023)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";

import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";
import type {
  RuntimeStatus,
  RuntimeStopCompletion,
  RuntimeStopDisposition,
  RuntimeTransition,
} from "./common_pb.js";
import { file_onequery_runtime_v1_common } from "./common_pb.js";

/**
 * Describes the file onequery/runtime/v1/control.proto.
 */
export const file_onequery_runtime_v1_control: GenFile /*@__PURE__*/ = fileDesc(
  "CiFvbmVxdWVyeS9ydW50aW1lL3YxL2NvbnRyb2wucHJvdG8SE29uZXF1ZXJ5LnJ1bnRpbWUudjEiEgoQR2V0U3RhdHVzUmVxdWVzdCJPChFHZXRTdGF0dXNSZXNwb25zZRI6CgZzdGF0dXMYASABKAsyIi5vbmVxdWVyeS5ydW50aW1lLnYxLlJ1bnRpbWVTdGF0dXNCBrpIA8gBASLiAQoLU3RvcFJlcXVlc3QSIQoMb3BlcmF0aW9uX2lkGAEgASgJQgu6SAjIAQFyA7ABARIdCgZyZWFzb24YAiABKAlCDbpICsgBAXIFEAEYgAQSTQoKY29tcGxldGlvbhgDIAEoDjIqLm9uZXF1ZXJ5LnJ1bnRpbWUudjEuUnVudGltZVN0b3BDb21wbGV0aW9uQg26SArIAQGCAQQQASAAEkIKDWdyYWNlX3RpbWVvdXQYBCABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb25CELpIDcgBAaoBByIDCKwCKgAi1wEKDFN0b3BSZXNwb25zZRJPCgtkaXNwb3NpdGlvbhgBIAEoDjIrLm9uZXF1ZXJ5LnJ1bnRpbWUudjEuUnVudGltZVN0b3BEaXNwb3NpdGlvbkINukgKyAEBggEEEAEgABI6CgZzdGF0dXMYAiABKAsyIi5vbmVxdWVyeS5ydW50aW1lLnYxLlJ1bnRpbWVTdGF0dXNCBrpIA8gBARI6Cgp0cmFuc2l0aW9uGAMgASgLMiYub25lcXVlcnkucnVudGltZS52MS5SdW50aW1lVHJhbnNpdGlvbiJXChJXYXRjaFN0YXR1c1JlcXVlc3QSHwoOYWZ0ZXJfc2VxdWVuY2UYASABKARCB7pIBDICKAASIAoQaW5jbHVkZV9zbmFwc2hvdBgCIAEoCEIGukgDyAEBIpsBChNXYXRjaFN0YXR1c1Jlc3BvbnNlEjYKCHNuYXBzaG90GAEgASgLMiIub25lcXVlcnkucnVudGltZS52MS5SdW50aW1lU3RhdHVzSAASPAoKdHJhbnNpdGlvbhgCIAEoCzImLm9uZXF1ZXJ5LnJ1bnRpbWUudjEuUnVudGltZVRyYW5zaXRpb25IAEIOCgVldmVudBIFukgCCAEyrgIKFVJ1bnRpbWVDb250cm9sU2VydmljZRJfCglHZXRTdGF0dXMSJS5vbmVxdWVyeS5ydW50aW1lLnYxLkdldFN0YXR1c1JlcXVlc3QaJi5vbmVxdWVyeS5ydW50aW1lLnYxLkdldFN0YXR1c1Jlc3BvbnNlIgOQAgESSwoEU3RvcBIgLm9uZXF1ZXJ5LnJ1bnRpbWUudjEuU3RvcFJlcXVlc3QaIS5vbmVxdWVyeS5ydW50aW1lLnYxLlN0b3BSZXNwb25zZRJnCgtXYXRjaFN0YXR1cxInLm9uZXF1ZXJ5LnJ1bnRpbWUudjEuV2F0Y2hTdGF0dXNSZXF1ZXN0Gigub25lcXVlcnkucnVudGltZS52MS5XYXRjaFN0YXR1c1Jlc3BvbnNlIgOQAgEwAWIIZWRpdGlvbnNw6Ac",
  [
    file_buf_validate_validate,
    file_google_protobuf_duration,
    file_onequery_runtime_v1_common,
  ]
);

/**
 * @generated from message onequery.runtime.v1.GetStatusRequest
 */
export type GetStatusRequest =
  Message<"onequery.runtime.v1.GetStatusRequest"> & {};

/**
 * Describes the message onequery.runtime.v1.GetStatusRequest.
 * Use `create(GetStatusRequestSchema)` to create a new message.
 */
export const GetStatusRequestSchema: GenMessage<GetStatusRequest> /*@__PURE__*/ =
  messageDesc(file_onequery_runtime_v1_control, 0);

/**
 * @generated from message onequery.runtime.v1.GetStatusResponse
 */
export type GetStatusResponse =
  Message<"onequery.runtime.v1.GetStatusResponse"> & {
    /**
     * @generated from field: onequery.runtime.v1.RuntimeStatus status = 1;
     */
    status?: RuntimeStatus;
  };

/**
 * Describes the message onequery.runtime.v1.GetStatusResponse.
 * Use `create(GetStatusResponseSchema)` to create a new message.
 */
export const GetStatusResponseSchema: GenMessage<GetStatusResponse> /*@__PURE__*/ =
  messageDesc(file_onequery_runtime_v1_control, 1);

/**
 * @generated from message onequery.runtime.v1.StopRequest
 */
export type StopRequest = Message<"onequery.runtime.v1.StopRequest"> & {
  /**
   * @generated from field: string operation_id = 1;
   */
  operationId: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;

  /**
   * @generated from field: onequery.runtime.v1.RuntimeStopCompletion completion = 3;
   */
  completion: RuntimeStopCompletion;

  /**
   * @generated from field: google.protobuf.Duration grace_timeout = 4;
   */
  graceTimeout?: Duration;
};

/**
 * Describes the message onequery.runtime.v1.StopRequest.
 * Use `create(StopRequestSchema)` to create a new message.
 */
export const StopRequestSchema: GenMessage<StopRequest> /*@__PURE__*/ =
  messageDesc(file_onequery_runtime_v1_control, 2);

/**
 * @generated from message onequery.runtime.v1.StopResponse
 */
export type StopResponse = Message<"onequery.runtime.v1.StopResponse"> & {
  /**
   * @generated from field: onequery.runtime.v1.RuntimeStopDisposition disposition = 1;
   */
  disposition: RuntimeStopDisposition;

  /**
   * @generated from field: onequery.runtime.v1.RuntimeStatus status = 2;
   */
  status?: RuntimeStatus;

  /**
   * @generated from field: onequery.runtime.v1.RuntimeTransition transition = 3;
   */
  transition?: RuntimeTransition;
};

/**
 * Describes the message onequery.runtime.v1.StopResponse.
 * Use `create(StopResponseSchema)` to create a new message.
 */
export const StopResponseSchema: GenMessage<StopResponse> /*@__PURE__*/ =
  messageDesc(file_onequery_runtime_v1_control, 3);

/**
 * @generated from message onequery.runtime.v1.WatchStatusRequest
 */
export type WatchStatusRequest =
  Message<"onequery.runtime.v1.WatchStatusRequest"> & {
    /**
     * @generated from field: uint64 after_sequence = 1;
     */
    afterSequence: bigint;

    /**
     * @generated from field: bool include_snapshot = 2;
     */
    includeSnapshot: boolean;
  };

/**
 * Describes the message onequery.runtime.v1.WatchStatusRequest.
 * Use `create(WatchStatusRequestSchema)` to create a new message.
 */
export const WatchStatusRequestSchema: GenMessage<WatchStatusRequest> /*@__PURE__*/ =
  messageDesc(file_onequery_runtime_v1_control, 4);

/**
 * @generated from message onequery.runtime.v1.WatchStatusResponse
 */
export type WatchStatusResponse =
  Message<"onequery.runtime.v1.WatchStatusResponse"> & {
    /**
     * @generated from oneof onequery.runtime.v1.WatchStatusResponse.event
     */
    event:
      | {
          /**
           * @generated from field: onequery.runtime.v1.RuntimeStatus snapshot = 1;
           */
          value: RuntimeStatus;
          case: "snapshot";
        }
      | {
          /**
           * @generated from field: onequery.runtime.v1.RuntimeTransition transition = 2;
           */
          value: RuntimeTransition;
          case: "transition";
        }
      | { case: undefined; value?: undefined };
  };

/**
 * Describes the message onequery.runtime.v1.WatchStatusResponse.
 * Use `create(WatchStatusResponseSchema)` to create a new message.
 */
export const WatchStatusResponseSchema: GenMessage<WatchStatusResponse> /*@__PURE__*/ =
  messageDesc(file_onequery_runtime_v1_control, 5);

/**
 * @generated from service onequery.runtime.v1.RuntimeControlService
 */
export const RuntimeControlService: GenService<{
  /**
   * @generated from rpc onequery.runtime.v1.RuntimeControlService.GetStatus
   */
  getStatus: {
    methodKind: "unary";
    input: typeof GetStatusRequestSchema;
    output: typeof GetStatusResponseSchema;
  };
  /**
   * @generated from rpc onequery.runtime.v1.RuntimeControlService.Stop
   */
  stop: {
    methodKind: "unary";
    input: typeof StopRequestSchema;
    output: typeof StopResponseSchema;
  };
  /**
   * @generated from rpc onequery.runtime.v1.RuntimeControlService.WatchStatus
   */
  watchStatus: {
    methodKind: "server_streaming";
    input: typeof WatchStatusRequestSchema;
    output: typeof WatchStatusResponseSchema;
  };
}> /*@__PURE__*/ = serviceDesc(file_onequery_runtime_v1_control, 0);
