type SqliteBootstrapClient = {
  exec(sql: string): unknown;
};

const SQLITE_BOOTSTRAP_STATEMENTS = [
  `PRAGMA foreign_keys = ON;`,
  `CREATE TABLE IF NOT EXISTS user (
    id TEXT PRIMARY KEY NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    email TEXT NOT NULL UNIQUE,
    email_verified INTEGER NOT NULL DEFAULT 0,
    image TEXT,
    name TEXT NOT NULL,
    updated_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer))
  );`,
  `CREATE TABLE IF NOT EXISTS organization (
    id TEXT PRIMARY KEY NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    logo TEXT,
    metadata TEXT,
    name TEXT NOT NULL,
    slug TEXT UNIQUE
  );`,
  `CREATE TABLE IF NOT EXISTS session (
    id TEXT PRIMARY KEY NOT NULL,
    active_organization_id TEXT REFERENCES organization(id) ON DELETE SET NULL,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    expires_at INTEGER NOT NULL,
    ip_address TEXT,
    token TEXT NOT NULL UNIQUE,
    updated_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    user_agent TEXT,
    user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE
  );`,
  `CREATE INDEX IF NOT EXISTS session_userId_idx ON session (user_id);`,
  `CREATE TABLE IF NOT EXISTS account (
    id TEXT PRIMARY KEY NOT NULL,
    access_token TEXT,
    access_token_expires_at INTEGER,
    account_id TEXT NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    id_token TEXT,
    password TEXT,
    provider_id TEXT NOT NULL,
    refresh_token TEXT,
    refresh_token_expires_at INTEGER,
    scope TEXT,
    updated_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE
  );`,
  `CREATE INDEX IF NOT EXISTS account_userId_idx ON account (user_id);`,
  `CREATE TABLE IF NOT EXISTS verification (
    id TEXT PRIMARY KEY NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    expires_at INTEGER NOT NULL,
    identifier TEXT NOT NULL,
    updated_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    value TEXT NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS verification_identifier_idx ON verification (identifier);`,
  `CREATE TABLE IF NOT EXISTS member (
    id TEXT PRIMARY KEY NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    organization_id TEXT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE
  );`,
  `CREATE INDEX IF NOT EXISTS member_organizationId_idx ON member (organization_id);`,
  `CREATE INDEX IF NOT EXISTS member_userId_idx ON member (user_id);`,
  `CREATE TABLE IF NOT EXISTS invitation (
    id TEXT PRIMARY KEY NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    email TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    inviter_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE,
    organization_id TEXT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    role TEXT,
    status TEXT NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS invitation_organizationId_idx ON invitation (organization_id);`,
  `CREATE INDEX IF NOT EXISTS invitation_email_idx ON invitation (email);`,
  `CREATE TABLE IF NOT EXISTS device_code (
    id TEXT PRIMARY KEY NOT NULL,
    client_id TEXT,
    device_code TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    last_polled_at INTEGER,
    polling_interval INTEGER,
    scope TEXT,
    status TEXT NOT NULL,
    user_code TEXT NOT NULL,
    user_id TEXT REFERENCES user(id) ON DELETE CASCADE
  );`,
  `CREATE UNIQUE INDEX IF NOT EXISTS device_code_device_code_key ON device_code (device_code);`,
  `CREATE UNIQUE INDEX IF NOT EXISTS device_code_user_code_key ON device_code (user_code);`,
  `CREATE INDEX IF NOT EXISTS device_code_user_id_idx ON device_code (user_id);`,
  `CREATE INDEX IF NOT EXISTS device_code_expires_at_idx ON device_code (expires_at);`,
  `CREATE TABLE IF NOT EXISTS data_sources (
    id TEXT PRIMARY KEY NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    credentials_encrypted TEXT NOT NULL,
    credentials_iv TEXT NOT NULL,
    error_message TEXT,
    last_used_at INTEGER,
    name TEXT NOT NULL,
    organization_id TEXT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    provider_account_id TEXT,
    scope TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    updated_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    use_as_data_source INTEGER NOT NULL DEFAULT 1,
    UNIQUE (organization_id, name)
  );`,
  `CREATE INDEX IF NOT EXISTS idx_data_sources_organization ON data_sources (organization_id);`,
  `CREATE INDEX IF NOT EXISTS idx_data_sources_provider ON data_sources (provider);`,
  `CREATE INDEX IF NOT EXISTS idx_data_sources_provider_account ON data_sources (provider, provider_account_id);`,
  `CREATE INDEX IF NOT EXISTS idx_data_sources_status ON data_sources (status);`,
  `CREATE TABLE IF NOT EXISTS connectors (
    connector_id TEXT PRIMARY KEY NOT NULL,
    auth_token_hash TEXT NOT NULL,
    connector_name TEXT NOT NULL,
    health_status TEXT,
    last_heartbeat_at INTEGER,
    last_seen_at INTEGER,
    metadata TEXT,
    organization_id TEXT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    registered_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    updated_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer))
  );`,
  `CREATE INDEX IF NOT EXISTS idx_connectors_organization ON connectors (organization_id);`,
  `CREATE INDEX IF NOT EXISTS idx_connectors_last_seen ON connectors (last_seen_at);`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_connectors_auth_token_hash_unique ON connectors (auth_token_hash);`,
  `CREATE TABLE IF NOT EXISTS connector_jobs (
    job_id TEXT PRIMARY KEY NOT NULL,
    completed_at INTEGER,
    connector_id TEXT NOT NULL REFERENCES connectors(connector_id) ON DELETE CASCADE,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    database TEXT NOT NULL,
    leased_at INTEGER,
    max_rows INTEGER,
    outcome TEXT,
    sql TEXT NOT NULL,
    status TEXT NOT NULL,
    timeout_ms INTEGER,
    updated_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    workgroup TEXT
  );`,
  `CREATE INDEX IF NOT EXISTS idx_connector_jobs_connector_created ON connector_jobs (connector_id, created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_connector_jobs_status_created ON connector_jobs (status, created_at);`,
  `CREATE TABLE IF NOT EXISTS data_source_query_costs (
    id TEXT PRIMARY KEY NOT NULL,
    actual_cost_usd REAL,
    actual_processed_bytes NUMERIC,
    billable_bytes NUMERIC,
    cache_hit INTEGER,
    connection_name TEXT NOT NULL,
    connector_id TEXT REFERENCES connectors(connector_id) ON DELETE CASCADE,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    currency TEXT NOT NULL DEFAULT 'USD',
    database TEXT,
    estimated_cost_usd REAL,
    estimated_processed_bytes NUMERIC,
    executed_at INTEGER NOT NULL,
    execution_time_ms INTEGER,
    job_id TEXT,
    location TEXT,
    organization_id TEXT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    pricing_model TEXT NOT NULL DEFAULT 'unknown',
    provider TEXT NOT NULL,
    query_execution_id TEXT,
    query_id TEXT NOT NULL,
    row_count INTEGER,
    tool_call_id TEXT NOT NULL,
    workgroup TEXT
  );`,
  `CREATE INDEX IF NOT EXISTS idx_data_source_query_costs_org ON data_source_query_costs (organization_id);`,
  `CREATE INDEX IF NOT EXISTS idx_data_source_query_costs_provider ON data_source_query_costs (provider);`,
  `CREATE INDEX IF NOT EXISTS idx_data_source_query_costs_executed_at ON data_source_query_costs (executed_at);`,
  `CREATE TABLE IF NOT EXISTS bigquery_query_costs (
    id TEXT PRIMARY KEY NOT NULL,
    actual_bytes_billed NUMERIC,
    actual_bytes_processed NUMERIC,
    actual_cost_usd REAL,
    cache_hit INTEGER,
    connection_name TEXT NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    currency TEXT NOT NULL DEFAULT 'USD',
    estimated_bytes_processed NUMERIC,
    estimated_cost_usd REAL,
    executed_at INTEGER NOT NULL,
    job_id TEXT,
    location TEXT,
    organization_id TEXT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    pricing_model TEXT NOT NULL DEFAULT 'unknown',
    query_id TEXT NOT NULL,
    tool_call_id TEXT NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_bigquery_query_costs_org ON bigquery_query_costs (organization_id);`,
  `CREATE INDEX IF NOT EXISTS idx_bigquery_query_costs_executed_at ON bigquery_query_costs (executed_at);`,
  `CREATE TABLE IF NOT EXISTS cli_query_actions (
    id TEXT PRIMARY KEY NOT NULL,
    organization_id TEXT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    actor_user_id TEXT NOT NULL,
    actor_email TEXT NOT NULL,
    actor_auth_mode TEXT NOT NULL,
    actor_membership_roles TEXT NOT NULL,
    request_id TEXT NOT NULL,
    action_type TEXT NOT NULL,
    stage TEXT NOT NULL DEFAULT 'received',
    status TEXT NOT NULL DEFAULT 'pending',
    usage_persistence_status TEXT NOT NULL DEFAULT 'not_started',
    source_key TEXT NOT NULL,
    source_id TEXT REFERENCES data_sources(id) ON DELETE SET NULL,
    provider TEXT,
    source_status TEXT,
    sql TEXT NOT NULL,
    normalized_sql TEXT,
    max_rows INTEGER,
    max_bytes INTEGER,
    cell_max_chars INTEGER,
    timeout_ms INTEGER,
    normalized_sql_changed INTEGER NOT NULL DEFAULT 0,
    row_count INTEGER,
    elapsed_ms INTEGER,
    error_detail TEXT,
    error_hint TEXT,
    retryable INTEGER,
    last_event_id TEXT,
    last_event_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    completed_at INTEGER,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    updated_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    version INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (id, last_event_id) REFERENCES cli_query_action_events(query_action_id, id),
    CONSTRAINT cli_query_actions_action_type_check CHECK (action_type in ('validate', 'execute')),
    CONSTRAINT cli_query_actions_actor_auth_mode_check CHECK (actor_auth_mode in ('browser_session', 'bearer_token')),
    CONSTRAINT cli_query_actions_stage_check CHECK (stage in ('received', 'load_source', 'validate_query', 'load_credentials', 'execute_query', 'persist_usage', 'completed')),
    CONSTRAINT cli_query_actions_status_check CHECK (status in ('pending', 'succeeded', 'source_not_found', 'source_not_queryable', 'query_rejected', 'query_preparation_failed', 'query_unavailable', 'query_timed_out', 'query_execution_failed')),
    CONSTRAINT cli_query_actions_usage_persistence_status_check CHECK (usage_persistence_status in ('not_started', 'succeeded', 'failed')),
    CONSTRAINT cli_query_actions_completed_stage_check CHECK ((stage = 'completed' and completed_at is not null) or (stage <> 'completed' and completed_at is null)),
    CONSTRAINT cli_query_actions_stage_status_alignment_check CHECK ((stage = 'completed' and status <> 'pending') or (stage <> 'completed' and status = 'pending')),
    CONSTRAINT cli_query_actions_pre_completion_usage_check CHECK (stage = 'completed' or usage_persistence_status = 'not_started')
  );`,
  `CREATE INDEX IF NOT EXISTS idx_cli_query_actions_org_created ON cli_query_actions (organization_id, created_at);`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_cli_query_actions_identity_unique ON cli_query_actions (id, organization_id, request_id, action_type, source_key);`,
  `CREATE INDEX IF NOT EXISTS idx_cli_query_actions_actor_user_id ON cli_query_actions (actor_user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_cli_query_actions_request_id ON cli_query_actions (request_id);`,
  `CREATE INDEX IF NOT EXISTS idx_cli_query_actions_source_id ON cli_query_actions (source_id);`,
  `CREATE INDEX IF NOT EXISTS idx_cli_query_actions_status ON cli_query_actions (status);`,
  `CREATE TABLE IF NOT EXISTS cli_query_action_events (
    id TEXT PRIMARY KEY NOT NULL,
    query_action_id TEXT NOT NULL REFERENCES cli_query_actions(id) ON DELETE CASCADE,
    organization_id TEXT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    actor_user_id TEXT NOT NULL,
    actor_email TEXT NOT NULL,
    actor_auth_mode TEXT NOT NULL,
    actor_membership_roles TEXT NOT NULL,
    request_id TEXT NOT NULL,
    action_type TEXT NOT NULL,
    event_type TEXT NOT NULL,
    stage TEXT NOT NULL,
    status TEXT NOT NULL,
    usage_persistence_status TEXT NOT NULL,
    source_key TEXT NOT NULL,
    source_id TEXT REFERENCES data_sources(id) ON DELETE SET NULL,
    provider TEXT,
    source_status TEXT,
    sql TEXT,
    normalized_sql TEXT,
    max_rows INTEGER,
    max_bytes INTEGER,
    cell_max_chars INTEGER,
    timeout_ms INTEGER,
    normalized_sql_changed INTEGER NOT NULL DEFAULT 0,
    row_count INTEGER,
    elapsed_ms INTEGER,
    error_detail TEXT,
    error_hint TEXT,
    retryable INTEGER,
    occurred_at INTEGER NOT NULL,
    causation_event_id TEXT REFERENCES cli_query_action_events(id) ON DELETE SET NULL,
    org_slug TEXT,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    FOREIGN KEY (query_action_id, organization_id, request_id, action_type, source_key) REFERENCES cli_query_actions(id, organization_id, request_id, action_type, source_key),
    FOREIGN KEY (query_action_id, causation_event_id) REFERENCES cli_query_action_events(query_action_id, id),
    CONSTRAINT cli_query_action_events_action_type_check CHECK (action_type in ('validate', 'execute')),
    CONSTRAINT cli_query_action_events_actor_auth_mode_check CHECK (actor_auth_mode in ('browser_session', 'bearer_token')),
    CONSTRAINT cli_query_action_events_event_type_check CHECK (event_type in ('action_received', 'source_loaded', 'source_not_found', 'source_not_queryable', 'query_validated', 'query_rejected', 'credentials_loaded', 'query_preparation_failed', 'query_executed', 'query_unavailable', 'query_timed_out', 'query_execution_failed', 'usage_persisted', 'usage_persist_failed')),
    CONSTRAINT cli_query_action_events_stage_check CHECK (stage in ('received', 'load_source', 'validate_query', 'load_credentials', 'execute_query', 'persist_usage', 'completed')),
    CONSTRAINT cli_query_action_events_status_check CHECK (status in ('pending', 'succeeded', 'source_not_found', 'source_not_queryable', 'query_rejected', 'query_preparation_failed', 'query_unavailable', 'query_timed_out', 'query_execution_failed')),
    CONSTRAINT cli_query_action_events_usage_persistence_status_check CHECK (usage_persistence_status in ('not_started', 'succeeded', 'failed')),
    CONSTRAINT cli_query_action_events_causation_not_self_check CHECK (causation_event_id is null or causation_event_id <> id),
    CONSTRAINT cli_query_action_events_sql_payload_check CHECK ((event_type = 'action_received' and sql is not null) or (event_type <> 'action_received' and sql is null)),
    CONSTRAINT cli_query_action_events_causation_chain_check CHECK ((event_type = 'action_received' and causation_event_id is null) or (event_type <> 'action_received' and causation_event_id is not null)),
    CONSTRAINT cli_query_action_events_validated_normalized_sql_check CHECK (event_type <> 'query_validated' or normalized_sql is not null),
    CONSTRAINT cli_query_action_events_lifecycle_check CHECK ((event_type = 'action_received' and stage = 'received' and status = 'pending' and usage_persistence_status = 'not_started') or (event_type = 'source_loaded' and stage = 'validate_query' and status = 'pending' and usage_persistence_status = 'not_started') or (event_type = 'source_not_found' and stage = 'completed' and status = 'source_not_found' and usage_persistence_status = 'not_started') or (event_type = 'source_not_queryable' and stage = 'completed' and status = 'source_not_queryable' and usage_persistence_status = 'not_started') or (event_type = 'query_validated' and ((action_type = 'validate' and stage = 'completed' and status = 'succeeded' and usage_persistence_status = 'not_started') or (action_type = 'execute' and stage = 'load_credentials' and status = 'pending' and usage_persistence_status = 'not_started'))) or (event_type = 'query_rejected' and stage = 'completed' and status = 'query_rejected' and usage_persistence_status = 'not_started') or (event_type = 'credentials_loaded' and stage = 'execute_query' and status = 'pending' and usage_persistence_status = 'not_started') or (event_type = 'query_preparation_failed' and stage = 'completed' and status = 'query_preparation_failed' and usage_persistence_status = 'not_started') or (event_type = 'query_executed' and stage = 'persist_usage' and status = 'pending' and usage_persistence_status = 'not_started') or (event_type = 'query_unavailable' and stage = 'completed' and status = 'query_unavailable' and usage_persistence_status = 'not_started') or (event_type = 'query_timed_out' and stage = 'completed' and status = 'query_timed_out' and usage_persistence_status = 'not_started') or (event_type = 'query_execution_failed' and stage = 'completed' and status = 'query_execution_failed' and usage_persistence_status = 'not_started') or (event_type = 'usage_persisted' and stage = 'completed' and status = 'succeeded' and usage_persistence_status = 'succeeded') or (event_type = 'usage_persist_failed' and stage = 'completed' and status = 'succeeded' and usage_persistence_status = 'failed'))
  );`,
  `CREATE INDEX IF NOT EXISTS idx_cli_query_action_events_action_occurred ON cli_query_action_events (query_action_id, occurred_at, id);`,
  `CREATE INDEX IF NOT EXISTS idx_cli_query_action_events_org_occurred ON cli_query_action_events (organization_id, occurred_at);`,
  `CREATE INDEX IF NOT EXISTS idx_cli_query_action_events_actor_user_id ON cli_query_action_events (actor_user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_cli_query_action_events_request_id ON cli_query_action_events (request_id);`,
  `CREATE INDEX IF NOT EXISTS idx_cli_query_action_events_causation ON cli_query_action_events (causation_event_id);`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_cli_query_action_events_action_id_unique ON cli_query_action_events (query_action_id, id);`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_cli_query_action_events_action_event_type_unique ON cli_query_action_events (query_action_id, event_type);`,
  `CREATE TABLE IF NOT EXISTS data_source_table_usage (
    id TEXT PRIMARY KEY NOT NULL,
    column_memos TEXT NOT NULL DEFAULT '{}',
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    data_source_id TEXT NOT NULL REFERENCES data_sources(id) ON DELETE CASCADE,
    formatted TEXT NOT NULL,
    generated_at INTEGER NOT NULL,
    memo_updated_at INTEGER,
    memo_updated_by TEXT REFERENCES user(id) ON DELETE SET NULL,
    organization_id TEXT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    schema_hash TEXT,
    table_lineage TEXT NOT NULL DEFAULT '{}',
    table_memos TEXT NOT NULL DEFAULT '{}',
    tables TEXT NOT NULL,
    updated_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer))
  );`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_data_source_table_usage_source ON data_source_table_usage (data_source_id);`,
  `CREATE INDEX IF NOT EXISTS idx_data_source_table_usage_org ON data_source_table_usage (organization_id);`,
  `CREATE INDEX IF NOT EXISTS idx_data_source_table_usage_provider ON data_source_table_usage (provider);`,
  `CREATE INDEX IF NOT EXISTS idx_data_source_table_usage_generated_at ON data_source_table_usage (generated_at);`,
  `CREATE TABLE IF NOT EXISTS organization_profiles (
    id TEXT PRIMARY KEY NOT NULL,
    organization_id TEXT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    north_star_metric TEXT,
    kpis TEXT NOT NULL DEFAULT '[]',
    website_url TEXT,
    monthly_budget_usd REAL,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    updated_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer))
  );`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_org_profiles_org ON organization_profiles (organization_id);`,
  `CREATE INDEX IF NOT EXISTS idx_org_profiles_created ON organization_profiles (created_at);`,
  `CREATE TABLE IF NOT EXISTS user_profiles (
    id TEXT PRIMARY KEY NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    updated_at INTEGER NOT NULL DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)),
    user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE
  );`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_user_profiles_user ON user_profiles (user_id);`,
];

export function bootstrapSqliteDatabase(client: SqliteBootstrapClient): void {
  for (const statement of SQLITE_BOOTSTRAP_STATEMENTS) {
    client.exec(statement);
  }
}
