import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { resolveWorkspaceDevPaths } from "@onequery/config/workspace-dev";

export interface WorkspaceDevSecretsInitResult {
  readonly created: boolean;
  readonly path: string;
}

function createBase64Secret(bytes: number): string {
  return randomBytes(bytes).toString("base64");
}

function createBase64UrlSecret(bytes: number): string {
  return randomBytes(bytes).toString("base64url");
}

function renderWorkspaceDevSecretsFile(): string {
  return [
    "# Generated by OneQuery local bootstrap.",
    "# This file is local-only and intentionally gitignored.",
    "",
    "[auth]",
    `secret = ${JSON.stringify(createBase64UrlSecret(32))}`,
    "",
    "[crypto]",
    `master_encryption_key = ${JSON.stringify(createBase64Secret(32))}`,
    "",
    "[connectors]",
    `enrollment_token = ${JSON.stringify(createBase64UrlSecret(32))}`,
    "",
  ].join("\n");
}

export function ensureWorkspaceDevSecretsFileSync(
  input: {
    readonly rootDir?: string;
  } = {}
): WorkspaceDevSecretsInitResult {
  const { secretsPath } = resolveWorkspaceDevPaths(input.rootDir);

  if (existsSync(secretsPath)) {
    return {
      created: false,
      path: secretsPath,
    };
  }

  mkdirSync(dirname(secretsPath), {
    recursive: true,
  });
  writeFileSync(secretsPath, renderWorkspaceDevSecretsFile(), "utf8");

  return {
    created: true,
    path: secretsPath,
  };
}
