[package]
name = "onequery-proto-build-support"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
buffa = { workspace = true, features = ["json"] }
buffa-codegen = { workspace = true }
connectrpc-build = { workspace = true }
onequery-utils = { workspace = true }

[lints]
workspace = true
