//! Builds explicit GitHub issue metadata from a saved diagnostic report.
//!
//! Normal command failures stay compact. Users opt into issue creation through
//! `onequery doctor report`, which can either print a `gh issue create`
//! fallback command or open a lightweight browser draft.

use std::path::Path;

use crate::diagnostics::DiagnosticSnapshot;

const GITHUB_NEW_ISSUE_URL: &str = "https://github.com/wordbricks/onequery/issues/new";
const GITHUB_REPOSITORY: &str = "wordbricks/onequery";
const ISSUE_LABELS: [&str; 2] = ["bug", "cli"];
const ISSUE_TEMPLATE_BODY: &str = "<!-- Generated by `onequery doctor report --last --open`. -->\n\n\
     Paste the redacted diagnostic report below before submitting.\n";

#[derive(Debug, Clone, Eq, PartialEq)]
pub(crate) struct IssueDraft {
    pub(crate) title: String,
    pub(crate) issue_url: String,
    pub(crate) github_command: String,
}

pub(crate) fn build_issue_draft(snapshot: &DiagnosticSnapshot, report_path: &Path) -> IssueDraft {
    let title = build_issue_title(snapshot);
    IssueDraft {
        issue_url: build_issue_url(&title),
        github_command: build_github_command(&title, report_path),
        title,
    }
}

fn build_issue_url(title: &str) -> String {
    let query = url::form_urlencoded::Serializer::new(String::new())
        .append_pair("labels", &ISSUE_LABELS.join(","))
        .append_pair("title", title)
        .append_pair("body", ISSUE_TEMPLATE_BODY)
        .finish();
    format!("{GITHUB_NEW_ISSUE_URL}?{query}")
}

fn build_issue_title(snapshot: &DiagnosticSnapshot) -> String {
    let summary = snapshot
        .error
        .code
        .as_deref()
        .unwrap_or(snapshot.error.title.as_str());
    format!("[cli] {summary}")
}

fn build_github_command(title: &str, report_path: &Path) -> String {
    format!(
        "gh issue create -R {GITHUB_REPOSITORY} --label {} --label {} --title {} --body-file {}",
        quote_shell_arg(ISSUE_LABELS[0]),
        quote_shell_arg(ISSUE_LABELS[1]),
        quote_shell_arg(title),
        quote_shell_arg(&report_path.display().to_string()),
    )
}

fn quote_shell_arg(value: &str) -> String {
    let mut quoted = String::with_capacity(value.len() + 2);
    quoted.push('"');
    for character in value.chars() {
        if matches!(character, '\\' | '"' | '$' | '`') {
            quoted.push('\\');
        }
        quoted.push(character);
    }
    quoted.push('"');
    quoted
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use pretty_assertions::assert_eq;

    use crate::diagnostics::DiagnosticSnapshot;
    use onequery_cli_core::error::CliError;
    use onequery_cli_core::error::ErrorStage;

    use super::build_issue_draft;

    fn sample_snapshot() -> DiagnosticSnapshot {
        DiagnosticSnapshot::from_error(
            &CliError::new(
                "query failed",
                "onequery query exec",
                ErrorStage::ExecuteQuery,
                "server rejected write query",
                vec![],
            )
            .with_code(Some("query_rejected".to_owned())),
            Some("query exec"),
            chrono::DateTime::parse_from_rfc3339("2026-04-23T03:12:11Z")
                .expect("expected timestamp")
                .with_timezone(&chrono::Utc),
        )
    }

    #[test]
    fn issue_draft_title_prefers_stable_error_code() {
        let draft = build_issue_draft(
            &sample_snapshot(),
            Path::new("/tmp/onequery-report-2026-04-23T03-20-00Z-req_123.md"),
        );

        assert_eq!(draft.title, "[cli] query_rejected");
    }

    #[test]
    fn issue_draft_url_uses_small_browser_payload() {
        let draft = build_issue_draft(
            &sample_snapshot(),
            Path::new("/tmp/onequery-report-2026-04-23T03-20-00Z-req_123.md"),
        );

        assert!(
            draft
                .issue_url
                .starts_with("https://github.com/wordbricks/onequery/issues/new?"),
            "unexpected base URL: {}",
            draft.issue_url
        );
        assert!(
            draft.issue_url.contains("labels=bug%2Ccli"),
            "missing labels: {}",
            draft.issue_url
        );
        assert!(
            draft.issue_url.contains("title=%5Bcli%5D+query_rejected"),
            "missing encoded title: {}",
            draft.issue_url
        );
        assert!(
            draft
                .issue_url
                .contains("Paste+the+redacted+diagnostic+report+below+before+submitting."),
            "missing short body template: {}",
            draft.issue_url
        );
    }

    #[test]
    fn issue_draft_github_command_uses_body_file() {
        let draft = build_issue_draft(
            &sample_snapshot(),
            Path::new("/tmp/onequery-report-2026-04-23T03-20-00Z-req_123.md"),
        );

        assert_eq!(
            draft.github_command,
            "gh issue create -R wordbricks/onequery --label \"bug\" --label \"cli\" --title \"[cli] query_rejected\" --body-file \"/tmp/onequery-report-2026-04-23T03-20-00Z-req_123.md\""
        );
    }

    #[test]
    fn issue_draft_title_falls_back_to_error_title_when_code_missing() {
        let snapshot = DiagnosticSnapshot::from_error(
            &CliError::new(
                "query failed",
                "onequery query exec",
                ErrorStage::ExecuteQuery,
                "server rejected write query",
                vec![],
            ),
            Some("query exec"),
            chrono::DateTime::parse_from_rfc3339("2026-04-23T03:12:11Z")
                .expect("expected timestamp")
                .with_timezone(&chrono::Utc),
        );
        let draft = build_issue_draft(
            &snapshot,
            Path::new("/tmp/onequery-report-2026-04-23T03-20-00Z-req_123.md"),
        );

        assert_eq!(draft.title, "[cli] query failed");
    }
}
