syntax = "proto3";

package onequery.cli.v1;

import "buf/validate/validate.proto";
import "onequery/cli/v1/common.proto";

message UseRequest {
  CliUseSource source = 1 [(buf.validate.field).enum.not_in = 0];
  optional string org_slug = 2 [
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.pattern = "^[a-z0-9]+(?:-[a-z0-9]+)*$"
  ];
}

message UseResponse {
  CliUseSource source = 1;
  string title = 2;
  string description = 3;
  CliContentFormat format = 4;
  string content = 5;
}

message CliUseContent {
  CliUseSource source = 1;
  string title = 2;
  string description = 3;
  CliContentFormat format = 4;
  string content = 5;
}

enum CliUseSource {
  CLI_USE_SOURCE_UNSPECIFIED = 0;
  CLI_USE_SOURCE_AMPLITUDE = 1;
  CLI_USE_SOURCE_GA = 2;
  CLI_USE_SOURCE_GITHUB = 3;
  CLI_USE_SOURCE_MIXPANEL = 4;
  CLI_USE_SOURCE_MONGODB = 5;
  CLI_USE_SOURCE_POSTHOG = 6;
  CLI_USE_SOURCE_SENTRY = 7;
}
