const SECOND_MS = 1000;
const MINUTE_MS = SECOND_MS * 60;
const HOUR_MS = MINUTE_MS * 60;

export const SHORT_QUERY_STALE_TIME_MS = SECOND_MS * 30;
export const DEFAULT_QUERY_STALE_TIME_MS = MINUTE_MS;
export const LONG_QUERY_STALE_TIME_MS = MINUTE_MS * 5;
export const SHORT_QUERY_RETRY_DELAY_MS = 300;
export const QUERY_GC_TIME_MS = MINUTE_MS * 5;
export const QUERY_PERSIST_MAX_AGE_MS = HOUR_MS * 24;
