"$schema" = "./node_modules/wrangler/config-schema.json"

# Note: This Worker name must match the Cloudflare Worker project name
# configured in Workers Builds for automatic GitHub deployments.
name = "onequery-landing"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-04-14"
logpush = true
preview_urls = true
routes = [{ pattern = "onequery.dev", custom_domain = true }]

[[kv_namespaces]]
binding = "SESSION"
id = "4eae4e6551dc4042950bd2270b09f772"

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 1
