/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedOrg_slugRouteImport } from './routes/_authenticated/$org_slug'
import { Route as AuthenticatedOrg_slugIndexRouteImport } from './routes/_authenticated/$org_slug/index'
import { Route as AuthenticatedOnboardingCreateOrgRouteImport } from './routes/_authenticated/onboarding/create-org'
import { Route as AuthenticatedOnboardingConnectDatabaseRouteImport } from './routes/_authenticated/onboarding/connect-database'
import { Route as AuthenticatedOrg_slugTeamRouteImport } from './routes/_authenticated/$org_slug/team'
import { Route as AuthenticatedOrg_slugSettingsRouteImport } from './routes/_authenticated/$org_slug/settings'
import { Route as AuthenticatedOrg_slugIntegrationsRouteImport } from './routes/_authenticated/$org_slug/integrations'
import { Route as AuthenticatedOrg_slugHomeRouteImport } from './routes/_authenticated/$org_slug/home'
import { Route as AuthenticatedOrg_slugBudgetRouteImport } from './routes/_authenticated/$org_slug/budget'
import { Route as AuthenticatedOrg_slugAuditRouteImport } from './routes/_authenticated/$org_slug/audit'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrg_slugRoute = AuthenticatedOrg_slugRouteImport.update({
  id: '/$org_slug',
  path: '/$org_slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrg_slugIndexRoute =
  AuthenticatedOrg_slugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrg_slugRoute,
  } as any)
const AuthenticatedOnboardingCreateOrgRoute =
  AuthenticatedOnboardingCreateOrgRouteImport.update({
    id: '/onboarding/create-org',
    path: '/onboarding/create-org',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingConnectDatabaseRoute =
  AuthenticatedOnboardingConnectDatabaseRouteImport.update({
    id: '/onboarding/connect-database',
    path: '/onboarding/connect-database',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrg_slugTeamRoute =
  AuthenticatedOrg_slugTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedOrg_slugRoute,
  } as any)
const AuthenticatedOrg_slugSettingsRoute =
  AuthenticatedOrg_slugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrg_slugRoute,
  } as any)
const AuthenticatedOrg_slugIntegrationsRoute =
  AuthenticatedOrg_slugIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedOrg_slugRoute,
  } as any)
const AuthenticatedOrg_slugHomeRoute =
  AuthenticatedOrg_slugHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedOrg_slugRoute,
  } as any)
const AuthenticatedOrg_slugBudgetRoute =
  AuthenticatedOrg_slugBudgetRouteImport.update({
    id: '/budget',
    path: '/budget',
    getParentRoute: () => AuthenticatedOrg_slugRoute,
  } as any)
const AuthenticatedOrg_slugAuditRoute =
  AuthenticatedOrg_slugAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedOrg_slugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/signin': typeof SigninRoute
  '/$org_slug': typeof AuthenticatedOrg_slugRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/$org_slug/audit': typeof AuthenticatedOrg_slugAuditRoute
  '/$org_slug/budget': typeof AuthenticatedOrg_slugBudgetRoute
  '/$org_slug/home': typeof AuthenticatedOrg_slugHomeRoute
  '/$org_slug/integrations': typeof AuthenticatedOrg_slugIntegrationsRoute
  '/$org_slug/settings': typeof AuthenticatedOrg_slugSettingsRoute
  '/$org_slug/team': typeof AuthenticatedOrg_slugTeamRoute
  '/onboarding/connect-database': typeof AuthenticatedOnboardingConnectDatabaseRoute
  '/onboarding/create-org': typeof AuthenticatedOnboardingCreateOrgRoute
  '/$org_slug/': typeof AuthenticatedOrg_slugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/signin': typeof SigninRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/$org_slug/audit': typeof AuthenticatedOrg_slugAuditRoute
  '/$org_slug/budget': typeof AuthenticatedOrg_slugBudgetRoute
  '/$org_slug/home': typeof AuthenticatedOrg_slugHomeRoute
  '/$org_slug/integrations': typeof AuthenticatedOrg_slugIntegrationsRoute
  '/$org_slug/settings': typeof AuthenticatedOrg_slugSettingsRoute
  '/$org_slug/team': typeof AuthenticatedOrg_slugTeamRoute
  '/onboarding/connect-database': typeof AuthenticatedOnboardingConnectDatabaseRoute
  '/onboarding/create-org': typeof AuthenticatedOnboardingCreateOrgRoute
  '/$org_slug': typeof AuthenticatedOrg_slugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/device': typeof DeviceRoute
  '/signin': typeof SigninRoute
  '/_authenticated/$org_slug': typeof AuthenticatedOrg_slugRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/_authenticated/$org_slug/audit': typeof AuthenticatedOrg_slugAuditRoute
  '/_authenticated/$org_slug/budget': typeof AuthenticatedOrg_slugBudgetRoute
  '/_authenticated/$org_slug/home': typeof AuthenticatedOrg_slugHomeRoute
  '/_authenticated/$org_slug/integrations': typeof AuthenticatedOrg_slugIntegrationsRoute
  '/_authenticated/$org_slug/settings': typeof AuthenticatedOrg_slugSettingsRoute
  '/_authenticated/$org_slug/team': typeof AuthenticatedOrg_slugTeamRoute
  '/_authenticated/onboarding/connect-database': typeof AuthenticatedOnboardingConnectDatabaseRoute
  '/_authenticated/onboarding/create-org': typeof AuthenticatedOnboardingCreateOrgRoute
  '/_authenticated/$org_slug/': typeof AuthenticatedOrg_slugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/device'
    | '/signin'
    | '/$org_slug'
    | '/auth/callback'
    | '/invite/$invitationId'
    | '/$org_slug/audit'
    | '/$org_slug/budget'
    | '/$org_slug/home'
    | '/$org_slug/integrations'
    | '/$org_slug/settings'
    | '/$org_slug/team'
    | '/onboarding/connect-database'
    | '/onboarding/create-org'
    | '/$org_slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/signin'
    | '/auth/callback'
    | '/invite/$invitationId'
    | '/$org_slug/audit'
    | '/$org_slug/budget'
    | '/$org_slug/home'
    | '/$org_slug/integrations'
    | '/$org_slug/settings'
    | '/$org_slug/team'
    | '/onboarding/connect-database'
    | '/onboarding/create-org'
    | '/$org_slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/device'
    | '/signin'
    | '/_authenticated/$org_slug'
    | '/auth/callback'
    | '/invite/$invitationId'
    | '/_authenticated/$org_slug/audit'
    | '/_authenticated/$org_slug/budget'
    | '/_authenticated/$org_slug/home'
    | '/_authenticated/$org_slug/integrations'
    | '/_authenticated/$org_slug/settings'
    | '/_authenticated/$org_slug/team'
    | '/_authenticated/onboarding/connect-database'
    | '/_authenticated/onboarding/create-org'
    | '/_authenticated/$org_slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  SigninRoute: typeof SigninRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$org_slug': {
      id: '/_authenticated/$org_slug'
      path: '/$org_slug'
      fullPath: '/$org_slug'
      preLoaderRoute: typeof AuthenticatedOrg_slugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$org_slug/': {
      id: '/_authenticated/$org_slug/'
      path: '/'
      fullPath: '/$org_slug/'
      preLoaderRoute: typeof AuthenticatedOrg_slugIndexRouteImport
      parentRoute: typeof AuthenticatedOrg_slugRoute
    }
    '/_authenticated/onboarding/create-org': {
      id: '/_authenticated/onboarding/create-org'
      path: '/onboarding/create-org'
      fullPath: '/onboarding/create-org'
      preLoaderRoute: typeof AuthenticatedOnboardingCreateOrgRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/connect-database': {
      id: '/_authenticated/onboarding/connect-database'
      path: '/onboarding/connect-database'
      fullPath: '/onboarding/connect-database'
      preLoaderRoute: typeof AuthenticatedOnboardingConnectDatabaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$org_slug/team': {
      id: '/_authenticated/$org_slug/team'
      path: '/team'
      fullPath: '/$org_slug/team'
      preLoaderRoute: typeof AuthenticatedOrg_slugTeamRouteImport
      parentRoute: typeof AuthenticatedOrg_slugRoute
    }
    '/_authenticated/$org_slug/settings': {
      id: '/_authenticated/$org_slug/settings'
      path: '/settings'
      fullPath: '/$org_slug/settings'
      preLoaderRoute: typeof AuthenticatedOrg_slugSettingsRouteImport
      parentRoute: typeof AuthenticatedOrg_slugRoute
    }
    '/_authenticated/$org_slug/integrations': {
      id: '/_authenticated/$org_slug/integrations'
      path: '/integrations'
      fullPath: '/$org_slug/integrations'
      preLoaderRoute: typeof AuthenticatedOrg_slugIntegrationsRouteImport
      parentRoute: typeof AuthenticatedOrg_slugRoute
    }
    '/_authenticated/$org_slug/home': {
      id: '/_authenticated/$org_slug/home'
      path: '/home'
      fullPath: '/$org_slug/home'
      preLoaderRoute: typeof AuthenticatedOrg_slugHomeRouteImport
      parentRoute: typeof AuthenticatedOrg_slugRoute
    }
    '/_authenticated/$org_slug/budget': {
      id: '/_authenticated/$org_slug/budget'
      path: '/budget'
      fullPath: '/$org_slug/budget'
      preLoaderRoute: typeof AuthenticatedOrg_slugBudgetRouteImport
      parentRoute: typeof AuthenticatedOrg_slugRoute
    }
    '/_authenticated/$org_slug/audit': {
      id: '/_authenticated/$org_slug/audit'
      path: '/audit'
      fullPath: '/$org_slug/audit'
      preLoaderRoute: typeof AuthenticatedOrg_slugAuditRouteImport
      parentRoute: typeof AuthenticatedOrg_slugRoute
    }
  }
}

interface AuthenticatedOrg_slugRouteChildren {
  AuthenticatedOrg_slugAuditRoute: typeof AuthenticatedOrg_slugAuditRoute
  AuthenticatedOrg_slugBudgetRoute: typeof AuthenticatedOrg_slugBudgetRoute
  AuthenticatedOrg_slugHomeRoute: typeof AuthenticatedOrg_slugHomeRoute
  AuthenticatedOrg_slugIntegrationsRoute: typeof AuthenticatedOrg_slugIntegrationsRoute
  AuthenticatedOrg_slugSettingsRoute: typeof AuthenticatedOrg_slugSettingsRoute
  AuthenticatedOrg_slugTeamRoute: typeof AuthenticatedOrg_slugTeamRoute
  AuthenticatedOrg_slugIndexRoute: typeof AuthenticatedOrg_slugIndexRoute
}

const AuthenticatedOrg_slugRouteChildren: AuthenticatedOrg_slugRouteChildren = {
  AuthenticatedOrg_slugAuditRoute: AuthenticatedOrg_slugAuditRoute,
  AuthenticatedOrg_slugBudgetRoute: AuthenticatedOrg_slugBudgetRoute,
  AuthenticatedOrg_slugHomeRoute: AuthenticatedOrg_slugHomeRoute,
  AuthenticatedOrg_slugIntegrationsRoute:
    AuthenticatedOrg_slugIntegrationsRoute,
  AuthenticatedOrg_slugSettingsRoute: AuthenticatedOrg_slugSettingsRoute,
  AuthenticatedOrg_slugTeamRoute: AuthenticatedOrg_slugTeamRoute,
  AuthenticatedOrg_slugIndexRoute: AuthenticatedOrg_slugIndexRoute,
}

const AuthenticatedOrg_slugRouteWithChildren =
  AuthenticatedOrg_slugRoute._addFileChildren(
    AuthenticatedOrg_slugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOrg_slugRoute: typeof AuthenticatedOrg_slugRouteWithChildren
  AuthenticatedOnboardingConnectDatabaseRoute: typeof AuthenticatedOnboardingConnectDatabaseRoute
  AuthenticatedOnboardingCreateOrgRoute: typeof AuthenticatedOnboardingCreateOrgRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrg_slugRoute: AuthenticatedOrg_slugRouteWithChildren,
  AuthenticatedOnboardingConnectDatabaseRoute:
    AuthenticatedOnboardingConnectDatabaseRoute,
  AuthenticatedOnboardingCreateOrgRoute: AuthenticatedOnboardingCreateOrgRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DeviceRoute: DeviceRoute,
  SigninRoute: SigninRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
