[package]
name = "onequery-proto-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
buffa = { workspace = true, features = ["json"] }
buffa-types = { workspace = true, features = ["json"] }
connectrpc = { workspace = true, features = ["client", "gzip"] }
http-body = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
