// Common CLI API types shared by the OneQuery Connect contract.

// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.js"
// @generated from file onequery/cli/v1/common.proto (package onequery.cli.v1, edition 2023)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type {
  GenEnum,
  GenFile,
  GenMessage,
} from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";
import type {
  BadRequest,
  ErrorInfo,
  Help,
  PreconditionFailure,
  QuotaFailure,
  ResourceInfo,
  RetryInfo,
} from "../../../google/rpc/error_details_pb.js";
import { file_google_rpc_error_details } from "../../../google/rpc/error_details_pb.js";

/**
 * Describes the file onequery/cli/v1/common.proto.
 */
export const file_onequery_cli_v1_common: GenFile /*@__PURE__*/ = fileDesc(
  "ChxvbmVxdWVyeS9jbGkvdjEvY29tbW9uLnByb3RvEg9vbmVxdWVyeS5jbGkudjEiTwoHQ2xpUGFnZRIfCgtuZXh0X2N1cnNvchgBIAEoCUIKukgHcgUQARiAIBIjCg5yZXR1cm5lZF9jb3VudBgCIAEoDUILukgIyAEBKgMY6AciRgoOQ2xpUGFnZVJlcXVlc3QSGAoFbGltaXQYASABKA1CCbpIBioEGGQoARIaCgZjdXJzb3IYAiABKAlCCrpIB3IFEAEYgCAidAoPQ2xpU2FuaXRpemF0aW9uEh4KB3Byb2ZpbGUYASABKAlCDbpICsgBAXIFEAEYgAESKgoPc2FuaXRpemVkX3BhdGhzGAIgAygJQhG6SA6SAQsQZCIHcgUQARiABBIVCg1yYXdfYXZhaWxhYmxlGAMgASgIIoMDCh5DbGlDb25uZWN0RXJyb3JEZXRhaWxSZWZlcmVuY2USKwoKZXJyb3JfaW5mbxgBIAEoCzIVLmdvb2dsZS5ycGMuRXJyb3JJbmZvSAASLQoLYmFkX3JlcXVlc3QYAiABKAsyFi5nb29nbGUucnBjLkJhZFJlcXVlc3RIABIrCgpyZXRyeV9pbmZvGAMgASgLMhUuZ29vZ2xlLnJwYy5SZXRyeUluZm9IABIxCg1yZXNvdXJjZV9pbmZvGAQgASgLMhguZ29vZ2xlLnJwYy5SZXNvdXJjZUluZm9IABI/ChRwcmVjb25kaXRpb25fZmFpbHVyZRgFIAEoCzIfLmdvb2dsZS5ycGMuUHJlY29uZGl0aW9uRmFpbHVyZUgAEjEKDXF1b3RhX2ZhaWx1cmUYBiABKAsyGC5nb29nbGUucnBjLlF1b3RhRmFpbHVyZUgAEiAKBGhlbHAYByABKAsyEC5nb29nbGUucnBjLkhlbHBIAEIPCgZkZXRhaWwSBbpIAggBKkwKDUNvbnRlbnRGb3JtYXQSHgoaQ09OVEVOVF9GT1JNQVRfVU5TUEVDSUZJRUQQABIbChdDT05URU5UX0ZPUk1BVF9NQVJLRE9XThABYghlZGl0aW9uc3DoBw",
  [file_buf_validate_validate, file_google_rpc_error_details]
);

/**
 * @generated from message onequery.cli.v1.CliPage
 */
export type CliPage = Message<"onequery.cli.v1.CliPage"> & {
  /**
   * @generated from field: string next_cursor = 1;
   */
  nextCursor: string;

  /**
   * @generated from field: uint32 returned_count = 2;
   */
  returnedCount: number;
};

/**
 * Describes the message onequery.cli.v1.CliPage.
 * Use `create(CliPageSchema)` to create a new message.
 */
export const CliPageSchema: GenMessage<CliPage> /*@__PURE__*/ = messageDesc(
  file_onequery_cli_v1_common,
  0
);

/**
 * Request pagination lives in a dedicated message so generated clients preserve
 * the "page omitted" vs "page present" boundary across language runtimes.
 *
 * @generated from message onequery.cli.v1.CliPageRequest
 */
export type CliPageRequest = Message<"onequery.cli.v1.CliPageRequest"> & {
  /**
   * @generated from field: uint32 limit = 1;
   */
  limit: number;

  /**
   * @generated from field: string cursor = 2;
   */
  cursor: string;
};

/**
 * Describes the message onequery.cli.v1.CliPageRequest.
 * Use `create(CliPageRequestSchema)` to create a new message.
 */
export const CliPageRequestSchema: GenMessage<CliPageRequest> /*@__PURE__*/ =
  messageDesc(file_onequery_cli_v1_common, 1);

/**
 * @generated from message onequery.cli.v1.CliSanitization
 */
export type CliSanitization = Message<"onequery.cli.v1.CliSanitization"> & {
  /**
   * @generated from field: string profile = 1;
   */
  profile: string;

  /**
   * @generated from field: repeated string sanitized_paths = 2;
   */
  sanitizedPaths: string[];

  /**
   * @generated from field: bool raw_available = 3;
   */
  rawAvailable: boolean;
};

/**
 * Describes the message onequery.cli.v1.CliSanitization.
 * Use `create(CliSanitizationSchema)` to create a new message.
 */
export const CliSanitizationSchema: GenMessage<CliSanitization> /*@__PURE__*/ =
  messageDesc(file_onequery_cli_v1_common, 2);

/**
 * Codegen anchor for standard Connect error-detail schemas used by the CLI
 * server and the Rust CLI client. Typed OneQuery CLI problems are identified by
 * google.rpc.ErrorInfo with domain "onequery.cli.v1".
 *
 * @generated from message onequery.cli.v1.CliConnectErrorDetailReference
 */
export type CliConnectErrorDetailReference =
  Message<"onequery.cli.v1.CliConnectErrorDetailReference"> & {
    /**
     * @generated from oneof onequery.cli.v1.CliConnectErrorDetailReference.detail
     */
    detail:
      | {
          /**
           * @generated from field: google.rpc.ErrorInfo error_info = 1;
           */
          value: ErrorInfo;
          case: "errorInfo";
        }
      | {
          /**
           * @generated from field: google.rpc.BadRequest bad_request = 2;
           */
          value: BadRequest;
          case: "badRequest";
        }
      | {
          /**
           * @generated from field: google.rpc.RetryInfo retry_info = 3;
           */
          value: RetryInfo;
          case: "retryInfo";
        }
      | {
          /**
           * @generated from field: google.rpc.ResourceInfo resource_info = 4;
           */
          value: ResourceInfo;
          case: "resourceInfo";
        }
      | {
          /**
           * @generated from field: google.rpc.PreconditionFailure precondition_failure = 5;
           */
          value: PreconditionFailure;
          case: "preconditionFailure";
        }
      | {
          /**
           * @generated from field: google.rpc.QuotaFailure quota_failure = 6;
           */
          value: QuotaFailure;
          case: "quotaFailure";
        }
      | {
          /**
           * @generated from field: google.rpc.Help help = 7;
           */
          value: Help;
          case: "help";
        }
      | { case: undefined; value?: undefined };
  };

/**
 * Describes the message onequery.cli.v1.CliConnectErrorDetailReference.
 * Use `create(CliConnectErrorDetailReferenceSchema)` to create a new message.
 */
export const CliConnectErrorDetailReferenceSchema: GenMessage<CliConnectErrorDetailReference> /*@__PURE__*/ =
  messageDesc(file_onequery_cli_v1_common, 3);

/**
 * @generated from enum onequery.cli.v1.ContentFormat
 */
export enum ContentFormat {
  /**
   * @generated from enum value: CONTENT_FORMAT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONTENT_FORMAT_MARKDOWN = 1;
   */
  MARKDOWN = 1,
}

/**
 * Describes the enum onequery.cli.v1.ContentFormat.
 */
export const ContentFormatSchema: GenEnum<ContentFormat> /*@__PURE__*/ =
  enumDesc(file_onequery_cli_v1_common, 0);
