// Organization lookup and listing messages for the CLI API.

// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.js"
// @generated from file onequery/cli/v1/org.proto (package onequery.cli.v1, edition 2023)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type {
  GenEnum,
  GenFile,
  GenMessage,
} from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";
import type { CliPage, CliPageRequest } from "./common_pb.js";
import { file_onequery_cli_v1_common } from "./common_pb.js";

/**
 * Describes the file onequery/cli/v1/org.proto.
 */
export const file_onequery_cli_v1_org: GenFile /*@__PURE__*/ = fileDesc(
  "ChlvbmVxdWVyeS9jbGkvdjEvb3JnLnByb3RvEg9vbmVxdWVyeS5jbGkudjEiSQoYTGlzdE9yZ2FuaXphdGlvbnNSZXF1ZXN0Ei0KBHBhZ2UYASABKAsyHy5vbmVxdWVyeS5jbGkudjEuQ2xpUGFnZVJlcXVlc3QilQEKGUxpc3RPcmdhbml6YXRpb25zUmVzcG9uc2USSAoNb3JnYW5pemF0aW9ucxgBIAMoCzInLm9uZXF1ZXJ5LmNsaS52MS5DbGlPcmdhbml6YXRpb25TdW1tYXJ5Qgi6SAWSAQIQZBIuCgRwYWdlGAIgASgLMhgub25lcXVlcnkuY2xpLnYxLkNsaVBhZ2VCBrpIA8gBASJVChZHZXRPcmdhbml6YXRpb25SZXF1ZXN0EjsKCG9yZ19zbHVnGAEgASgJQim6SCbIAQFyIRABGP8BMhpeW2EtejAtOV0rKD86LVthLXowLTldKykqJCKBAgoXR2V0T3JnYW5pemF0aW9uUmVzcG9uc2USNwoEc2x1ZxgBIAEoCUIpukgmyAEBciEQARj/ATIaXlthLXowLTldKyg/Oi1bYS16MC05XSspKiQSGwoEbmFtZRgCIAEoCUINukgKyAEBcgUQARj/ARJFCgVyb2xlcxgDIAMoDjIhLm9uZXF1ZXJ5LmNsaS52MS5Pcmdhbml6YXRpb25Sb2xlQhO6SBCSAQ0QIBgBIgeCAQQQASAAEkkKDGNhcGFiaWxpdGllcxgEIAMoDjIeLm9uZXF1ZXJ5LmNsaS52MS5PcmdDYXBhYmlsaXR5QhO6SBCSAQ0QIBgBIgeCAQQQASAAIm4KFkNsaU9yZ2FuaXphdGlvblN1bW1hcnkSNwoEc2x1ZxgBIAEoCUIpukgmyAEBciEQARj/ATIaXlthLXowLTldKyg/Oi1bYS16MC05XSspKiQSGwoEbmFtZRgCIAEoCUINukgKyAEBcgUQARj/ASreAgoNT3JnQ2FwYWJpbGl0eRIeChpPUkdfQ0FQQUJJTElUWV9VTlNQRUNJRklFRBAAEhsKF09SR19DQVBBQklMSVRZX09SR19MSVNUEAESGwoXT1JHX0NBUEFCSUxJVFlfT1JHX1JFQUQQAhIhCh1PUkdfQ0FQQUJJTElUWV9TT1VSQ0VfQ09OTkVDVBADEh4KGk9SR19DQVBBQklMSVRZX1NPVVJDRV9MSVNUEAQSHgoaT1JHX0NBUEFCSUxJVFlfU09VUkNFX1JFQUQQBRIgChxPUkdfQ0FQQUJJTElUWV9RVUVSWV9FWEVDVVRFEAYSJgoiT1JHX0NBUEFCSUxJVFlfU09VUkNFX0FQSV9ERVNDUklCRRAHEiUKIU9SR19DQVBBQklMSVRZX1NPVVJDRV9BUElfRVhFQ1VURRAIEh8KG09SR19DQVBBQklMSVRZX1NPVVJDRV9XUklURRAJKo0BChBPcmdhbml6YXRpb25Sb2xlEiEKHU9SR0FOSVpBVElPTl9ST0xFX1VOU1BFQ0lGSUVEEAASGwoXT1JHQU5JWkFUSU9OX1JPTEVfT1dORVIQARIbChdPUkdBTklaQVRJT05fUk9MRV9BRE1JThACEhwKGE9SR0FOSVpBVElPTl9ST0xFX01FTUJFUhADYghlZGl0aW9uc3DoBw",
  [file_buf_validate_validate, file_onequery_cli_v1_common]
);

/**
 * @generated from message onequery.cli.v1.ListOrganizationsRequest
 */
export type ListOrganizationsRequest =
  Message<"onequery.cli.v1.ListOrganizationsRequest"> & {
    /**
     * @generated from field: onequery.cli.v1.CliPageRequest page = 1;
     */
    page?: CliPageRequest;
  };

/**
 * Describes the message onequery.cli.v1.ListOrganizationsRequest.
 * Use `create(ListOrganizationsRequestSchema)` to create a new message.
 */
export const ListOrganizationsRequestSchema: GenMessage<ListOrganizationsRequest> /*@__PURE__*/ =
  messageDesc(file_onequery_cli_v1_org, 0);

/**
 * @generated from message onequery.cli.v1.ListOrganizationsResponse
 */
export type ListOrganizationsResponse =
  Message<"onequery.cli.v1.ListOrganizationsResponse"> & {
    /**
     * @generated from field: repeated onequery.cli.v1.CliOrganizationSummary organizations = 1;
     */
    organizations: CliOrganizationSummary[];

    /**
     * @generated from field: onequery.cli.v1.CliPage page = 2;
     */
    page?: CliPage;
  };

/**
 * Describes the message onequery.cli.v1.ListOrganizationsResponse.
 * Use `create(ListOrganizationsResponseSchema)` to create a new message.
 */
export const ListOrganizationsResponseSchema: GenMessage<ListOrganizationsResponse> /*@__PURE__*/ =
  messageDesc(file_onequery_cli_v1_org, 1);

/**
 * @generated from message onequery.cli.v1.GetOrganizationRequest
 */
export type GetOrganizationRequest =
  Message<"onequery.cli.v1.GetOrganizationRequest"> & {
    /**
     * @generated from field: string org_slug = 1;
     */
    orgSlug: string;
  };

/**
 * Describes the message onequery.cli.v1.GetOrganizationRequest.
 * Use `create(GetOrganizationRequestSchema)` to create a new message.
 */
export const GetOrganizationRequestSchema: GenMessage<GetOrganizationRequest> /*@__PURE__*/ =
  messageDesc(file_onequery_cli_v1_org, 2);

/**
 * @generated from message onequery.cli.v1.GetOrganizationResponse
 */
export type GetOrganizationResponse =
  Message<"onequery.cli.v1.GetOrganizationResponse"> & {
    /**
     * @generated from field: string slug = 1;
     */
    slug: string;

    /**
     * @generated from field: string name = 2;
     */
    name: string;

    /**
     * @generated from field: repeated onequery.cli.v1.OrganizationRole roles = 3;
     */
    roles: OrganizationRole[];

    /**
     * @generated from field: repeated onequery.cli.v1.OrgCapability capabilities = 4;
     */
    capabilities: OrgCapability[];
  };

/**
 * Describes the message onequery.cli.v1.GetOrganizationResponse.
 * Use `create(GetOrganizationResponseSchema)` to create a new message.
 */
export const GetOrganizationResponseSchema: GenMessage<GetOrganizationResponse> /*@__PURE__*/ =
  messageDesc(file_onequery_cli_v1_org, 3);

/**
 * @generated from message onequery.cli.v1.CliOrganizationSummary
 */
export type CliOrganizationSummary =
  Message<"onequery.cli.v1.CliOrganizationSummary"> & {
    /**
     * @generated from field: string slug = 1;
     */
    slug: string;

    /**
     * @generated from field: string name = 2;
     */
    name: string;
  };

/**
 * Describes the message onequery.cli.v1.CliOrganizationSummary.
 * Use `create(CliOrganizationSummarySchema)` to create a new message.
 */
export const CliOrganizationSummarySchema: GenMessage<CliOrganizationSummary> /*@__PURE__*/ =
  messageDesc(file_onequery_cli_v1_org, 4);

/**
 * @generated from enum onequery.cli.v1.OrgCapability
 */
export enum OrgCapability {
  /**
   * @generated from enum value: ORG_CAPABILITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ORG_CAPABILITY_ORG_LIST = 1;
   */
  ORG_LIST = 1,

  /**
   * @generated from enum value: ORG_CAPABILITY_ORG_READ = 2;
   */
  ORG_READ = 2,

  /**
   * @generated from enum value: ORG_CAPABILITY_SOURCE_CONNECT = 3;
   */
  SOURCE_CONNECT = 3,

  /**
   * @generated from enum value: ORG_CAPABILITY_SOURCE_LIST = 4;
   */
  SOURCE_LIST = 4,

  /**
   * @generated from enum value: ORG_CAPABILITY_SOURCE_READ = 5;
   */
  SOURCE_READ = 5,

  /**
   * @generated from enum value: ORG_CAPABILITY_QUERY_EXECUTE = 6;
   */
  QUERY_EXECUTE = 6,

  /**
   * @generated from enum value: ORG_CAPABILITY_SOURCE_API_DESCRIBE = 7;
   */
  SOURCE_API_DESCRIBE = 7,

  /**
   * @generated from enum value: ORG_CAPABILITY_SOURCE_API_EXECUTE = 8;
   */
  SOURCE_API_EXECUTE = 8,

  /**
   * @generated from enum value: ORG_CAPABILITY_SOURCE_WRITE = 9;
   */
  SOURCE_WRITE = 9,
}

/**
 * Describes the enum onequery.cli.v1.OrgCapability.
 */
export const OrgCapabilitySchema: GenEnum<OrgCapability> /*@__PURE__*/ =
  enumDesc(file_onequery_cli_v1_org, 0);

/**
 * @generated from enum onequery.cli.v1.OrganizationRole
 */
export enum OrganizationRole {
  /**
   * @generated from enum value: ORGANIZATION_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ORGANIZATION_ROLE_OWNER = 1;
   */
  OWNER = 1,

  /**
   * @generated from enum value: ORGANIZATION_ROLE_ADMIN = 2;
   */
  ADMIN = 2,

  /**
   * @generated from enum value: ORGANIZATION_ROLE_MEMBER = 3;
   */
  MEMBER = 3,
}

/**
 * Describes the enum onequery.cli.v1.OrganizationRole.
 */
export const OrganizationRoleSchema: GenEnum<OrganizationRole> /*@__PURE__*/ =
  enumDesc(file_onequery_cli_v1_org, 1);
