name: Evergreen

on:
  schedule:
    # Every 6AM on Monday KST (9PM Sunday UTC)
    - cron: "0 21 * * 0"

  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - run: rm bun.lock

      - run: bun bump

      - run: bun i --ignore-scripts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Bump dependencies
          token: ${{ secrets.EVERGREEN_TOKEN }}
